name: Docker Build and Push

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
        default: 'main'  # Default branch name

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker credential helper
        run: |
              sudo apt-get install -y gnupg2 pass
              curl -fsSL https://github.com/docker/docker-credential-helpers/releases/download/v0.7.6/docker-credential-secretservice-v0.7.6-amd64.tar.gz | sudo tar -xz -C /usr/local/bin/
              mkdir -p ~/.docker
              mv /usr/local/bin/docker-credential-secretservice ~/.docker/docker-credential-secretservice
              chmod +x ~/.docker/docker-credential-secretservice
              docker-credential-secretservice version
              docker-credential-secretservice store <(echo "{\"Username\":\"${{ secrets.DOCKER_USERNAME }}\",\"Secret\":\"${{ secrets.DOCKER_PASSWORD }}\"}")


      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/nature-frontend-client
          IMAGE_TAG: latest
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -t $IMAGE_NAME:$IMAGE_TAG . --push
